# .github/workflows/deploy.yml (Version Baseline)
name: Deploy Python FastAPI App (Baseline) to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  VENV_NAME: 'antenv'
  API_SOURCE_DIR: '${{ github.workspace }}/api'
  DEPLOY_PACKAGE_NAME: 'api_deploy_package.zip'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and activate virtual environment
      run: |
        python -m venv $VENV_NAME
        $VENV_NAME/bin/python -m pip install --upgrade pip wheel

    - name: Install dependencies into virtual environment
      run: |
        $VENV_NAME/bin/pip install -r $API_SOURCE_DIR/requirements.txt

    # --- ÉTAPE spaCy SUPPRIMÉE ---

    - name: List files and venv contents
      run: |
        echo "--- Listing Root Directory (${{ github.workspace }}) ---"; ls -lR ${{ github.workspace }}; echo "---";
        echo "--- Listing API Directory ($API_SOURCE_DIR) ---"; ls -lR $API_SOURCE_DIR; echo "---";
        echo "--- Listing VENV bin ($VENV_NAME/bin) ---"; ls -l $VENV_NAME/bin || echo "Venv bin not found"; echo "---";

    - name: Run tests
      run: |
         $VENV_NAME/bin/pytest $API_SOURCE_DIR/tests/

    # --- MODIFIÉ : Créer l'archive ZIP (Baseline) ---
    - name: Create deployment package
      run: |
        echo "Création de l'archive ZIP (Baseline) pour le déploiement..."
        mkdir deploy_package
        # Copier les fichiers nécessaires pour la baseline
        cp $API_SOURCE_DIR/main.py deploy_package/
        cp $API_SOURCE_DIR/requirements.txt deploy_package/
        cp $API_SOURCE_DIR/baseline_pipeline.joblib deploy_package/ # Copier le pipeline joblib
        # S'assurer qu'aucun fichier lourd restant n'est copié accidentellement
        echo "Contenu du package à zipper :"
        ls -l deploy_package/
        cd deploy_package
        zip -r ../${{ env.DEPLOY_PACKAGE_NAME }} .
        cd ..
        echo "Archive $DEPLOY_PACKAGE_NAME créée."

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'airparadis-sentiment-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.DEPLOY_PACKAGE_NAME }}' # Déployer le zip